// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnSXsApUfLh9nrXXB9HLqSwCWz9nAQ3B4',
    appId: '1:110882854991:web:1a1d932c7d54491f7b723a',
    messagingSenderId: '110882854991',
    projectId: 'login-f5427',
    authDomain: 'login-f5427.firebaseapp.com',
    databaseURL: 'https://login-f5427-default-rtdb.firebaseio.com',
    storageBucket: 'login-f5427.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATvYhAtQjF0M2AZK7Ri5VvPuBH1AcZhSE',
    appId: '1:110882854991:ios:008a0b0bd07068277b723a',
    messagingSenderId: '110882854991',
    projectId: 'login-f5427',
    databaseURL: 'https://login-f5427-default-rtdb.firebaseio.com',
    storageBucket: 'login-f5427.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
